### ISSUE TITLE
Write a git hook to "block release" for each city on every master merge

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#120]
This ticket is related to the new email block that Kate demoed on 05/11/2020

**Comment by k8reindeer** [comment]
Some thoughts/context on this ticket:

We already have a git hook in `.github/workflows/udpdate-now.yaml`. This ticket is to write another git hook that also triggers on merges to master, but instead of deploying to Vercel, it runs `block release`.

We'll probably want to keep a list somewhere of all the cities this should run for, similar to the list of all websites we're running in `scripts/update-all.js`. These should probably be different lists since the set of cities we deploy the email block to may be different than the set of cities we deploy a website for. For example, Concord doesn't have emailing yet, and there's no reason to give the "landing page" CMS airtable base an emailing block. 

Writing the script to run `block release` should be pretty straightforward. Here are the docs for how to run a release to a new remote:  https://airtable.com/developers/blocks/guides/run-in-multiple-bases

Then, whenever we want to add the block to a new city, we'll need to 
* `block add-remote [etc, see docs above]`
* check in the `.block/cityname.remote.json` file to github
* add the city's name to the list in the script
and then that city's block will receive all updates. Once we build the deploy script, we should put the above procedure in a README (or whatever else we're using for internal developer documentation) so we remember to do this! (This is not the kind of information we'd need to share with partner developers -- this procedure would only need to be done for cities that we are managing ourselves)

The only snag I can think of is, it doesn't look like you can provide the airtable API key in the command line of a `block` command, but this documentation: https://www.npmjs.com/package/@airtable/blocks-cli indicates you can use `block set-api-key` There's currently a github secret called  AIRTABLE_API_KEY, so we should just use that value. Important to make that however we're doing this, we don't expose the API key

**Comment by keithk** [comment]
Verified that using the API in the command line does _not_ leak the secret, so going to dig into this a little more!

**Comment by neelamsaboo** [comment]
@keithk , is this still relevant or can be closed?
